twig:
    paths: ['%kernel.project_dir%/src/UI/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
            - bootstrap_3_layout.html.twig
    globals:
        google_maps: https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyBDFGff7mQ3mWhfZ5IYuqPxsCd049nqIn4
