default:
    suites:
        default:
            contexts:
                - behatch:context:json
                - behatch:context:rest
                - Behat\MinkExtension\Context\MinkContext
                - App\Tests\Behat\TravelContext

    extensions:
        FriendsOfBehat\SymfonyExtension:
            kernel:
                environment: test
        Behatch\Extension: ~
        Behat\MinkExtension:
            sessions:
                default:
                    symfony: ~

